#!/bin/bash

set -eux

docker rm -f osoba
docker build \
  -f Dockerfile \
  --target osoba-builder \
  ./ -t osoba
docker run -itd \
  --network proxy \
  --volumes-from data-cert \
  --volumes-from data-h2o-conf \
  --volumes-from data-www \
  --volumes-from data-jwt-secret \
  --name osoba osoba \
  /osoba/osoba
